# Generated by Django 4.1.5 on 2023-02-03 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='total_cost',
        ),
    ]
