# Generated by Django 4.1.5 on 2023-02-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='pph',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
