# Generated by Django 4.1.5 on 2023-02-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['item'], 'verbose_name': 'inventory'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name'], 'verbose_name': 'item'},
        ),
        migrations.AddField(
            model_name='item',
            name='serial_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='distributor',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
