# Generated by Django 4.1.5 on 2023-02-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_alter_inventory_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='distributor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='serial_number',
            field=models.IntegerField(default=0),
        ),
    ]
