# Generated by Django 4.1.5 on 2023-02-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_alter_item_description_alter_item_distributor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
