# Generated by Django 4.1.5 on 2023-02-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0004_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='distributor',
            field=models.CharField(default='', max_length=30),
        ),
    ]
