# Generated by Django 4.1.5 on 2023-02-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0006_alter_item_description_alter_item_distributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='item',
            name='item_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
