# Generated by Django 4.1.5 on 2023-02-05 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0010_remove_item_item_count_remove_product_item_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name'], 'verbose_name': 'items'},
        ),
        migrations.AlterModelOptions(
            name='itemstock',
            options={'verbose_name': 'stock_items'},
        ),
        migrations.RenameField(
            model_name='productneeds',
            old_name='items_needed',
            new_name='items_required',
        ),
    ]
