# Generated by Django 4.1.5 on 2023-03-27 23:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0011_alter_item_options_alter_itemstock_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'products'},
        ),
        migrations.AlterModelOptions(
            name='productstock',
            options={'verbose_name': 'stock_products'},
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
