# Generated by Django 4.1.5 on 2023-03-27 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0012_alter_product_options_alter_productstock_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstock',
            old_name='current_count',
            new_name='product_count',
        ),
    ]
