# Generated by Django 4.1.5 on 2023-03-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0015_alter_itemstock_options_alter_productstock_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstock',
            name='product',
        ),
        migrations.AddField(
            model_name='item',
            name='item_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ItemStock',
        ),
        migrations.DeleteModel(
            name='ProductStock',
        ),
    ]
