# Generated by Django 4.1.5 on 2023-03-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0016_remove_productstock_product_item_item_count_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductNeeds',
            new_name='Product_Items',
        ),
        migrations.RenameField(
            model_name='product_items',
            old_name='items_required',
            new_name='item_qty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='items_needed',
        ),
        migrations.AddField(
            model_name='product',
            name='items',
            field=models.ManyToManyField(through='inventory_app.Product_Items', to='inventory_app.item'),
        ),
    ]
