# Generated by Django 4.1.5 on 2023-04-03 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0017_rename_productneeds_product_items_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product_items',
            unique_together={('product', 'item')},
        ),
    ]
