# Generated by Django 4.1.5 on 2023-04-05 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0019_alter_product_items_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product_items',
            unique_together={('product', 'item')},
        ),
    ]
