# Generated by Django 4.1.5 on 2023-04-05 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0021_remove_product_items_id_alter_product_items_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_items',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_items',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.product', unique=True),
        ),
    ]
