# Generated by Django 4.1.5 on 2023-04-05 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0022_product_items_id_alter_product_items_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_items',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.product'),
        ),
    ]
