# Generated by Django 4.1.5 on 2023-04-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0023_alter_product_items_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='items',
            field=models.ManyToManyField(related_name='products', through='inventory_app.Product_Items', to='inventory_app.item'),
        ),
    ]
