# Generated by Django 4.1.5 on 2023-04-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0024_alter_product_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name'], 'verbose_name': 'item'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'product'},
        ),
        migrations.AlterModelOptions(
            name='product_items',
            options={'verbose_name': 'recipe'},
        ),
        migrations.AlterField(
            model_name='product_items',
            name='item_qty',
            field=models.IntegerField(default=1),
        ),
    ]
